apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: https://argocd-{REPLACE_VCLUSTER_NAME}.us.demo.dev
  service.webhook.vcluster-platform: |
    url: https://{REPLACE_VCLUSTER_NAME}.us.demo.dev
    headers:
    - name: Authorization
      value: "Bearer $accessKey"
    - name: User-Agent
      value: "vCluster Platform"
  template.wakeup-vcluster: |
    webhook:
      vcluster-platform:
        method: POST
        path: /kubernetes/project/{{ index .app.metadata.labels "vclusterProjectId" }}/virtualcluster/{{ index .app.metadata.labels "vclusterName" }}
  trigger.wakeup-vcluster: |
    - description: "Notify when an application becomes OutOfSync"
      when: app.status.sync.status == 'OutOfSync'
      send: [wakeup-vcluster]
