kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: default-template
spec:
  displayName: Default Virtual Cluster Template
  description: This virtual cluster template deploys a vCluster with embedded etcd and integrated CoreDNS.
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro: {}
    helmRelease:
      chart:
        version: 0.20.0
      values: |-
        sync:
          toHost:
            ingresses:
              enabled: true

        # Checkout https://vcluster.com/pro/docs/ for more config options
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  versions:
    - template:
        metadata:
          annotations:
            sleepmode.loft.sh/ignore-user-agents: argo*
        instanceTemplate:
          metadata:
            annotations:
              loft.sh/custom-links: >-
                Helm-Dashboard=https://helm-dashboard-{{ .Values.loft.virtualClusterName }}-{{ .Values.loft.clusterAnnotations.domainPrefix }}.{{ .Values.loft.clusterAnnotations.domain }}
            labels:
              env: '{{ .Values.env }}'
              team: '{{ .Values.loft.project }}'
        apps:
          - name: helm-dashboard
            namespace: helm-dashboard
        pro:
          enabled: true
        helmRelease:
          chart:
            name: vcluster
            repo: https://loft-demos.github.io/vcluster-charts
            version: 0.23.0
          values: |
            external:
              platform:
                autoSleep:
                  afterInactivity: 1620
                  timezone: America/New_York
                  autoWakeup:
                    schedule: 11 7-17 * * 1-5
                autoDelete:
                  afterInactivity: 1800000
                  
            sync:
              toHost:
                pods:
                  patches:
                    - path: metadata.annotations
                      expression: 'value["loft.demos/business_unit"]="{{ .Values.loft.project }}";value'
                ingresses:
                  enabled: true
                secrets:
                  all: true
            
            #plugins:
              #rancher:
                #image: ghcr.io/loft-sh/rancher-nodeless-plugin:0.0.5

            controlPlane:
              advanced:
                workloadServiceAccount:
                  enabled: true
                  imagePullSecrets:
                  - name: "hook-image-pull-secret"
              statefulSet:
                annotations:
                  demo.loft.sh/pvClaimName: '{{ .Values.pvClaimName }}'
                labels:
                  env: '{{ .Values.env }}'
                  team: '{{ .Values.loft.project }}'
                  pvClaimName: '{{ .Values.pvClaimName }}'
                resources:
                  # Limits are resource limits for the container
                  limits:
                    ephemeral-storage: 8Gi
                    memory: 2Gi
                    cpu: 1
                image:
                  repository: "loft-demos/vcluster-pro"
                  tag: "0.24.0-rc.1-k8s.{{ .Values.k8sVersion }}"
                persistence:
                  volumeClaim:
                    storageClass: "standard-rwo"
              # Use an embedded managed etcd server instead of using the default SQLite backend
              backingStore:
                etcd:
                  embedded:
                    enabled: true
              coredns:
                embedded: true

            # Checkout https://vcluster.com/pro/docs/ for more config options
        accessPoint:
          ingress: {}
        spaceTemplate:
          metadata: {}
          objects: |
            apiVersion: v1
            kind: Secret
            metadata:
              name: hook-image-pull-secret
              labels:
                loft.sh/project-secret-name: ghcr-login-secret
            data:
              .dockerconfigjson: e30K
            type: kubernetes.io/dockerconfigjson
      parameters:
        - variable: k8sVersion
          label: k8sVersion
          description: Please select Kubernetes version
          options:
            - v1.32.2
            - v1.31.6
            - v1.30.10
            - v1.29.14
          defaultValue: v1.31.6
          section: Kubernetes Environment
        - variable: pvClaimName
          label: Persistent Volume Claim Name
          description: >-
            The claim to use as the persistent volume for the vCluster `StatefulSet`
          required: true
          defaultValue: "pvclaim-id"
          section: Kubernetes Environment
        - variable: env
          label: Deployment Environment
          description: >-
            Environment for deployments for this vCluster used as cluster label
            for Argo CD ApplicationSet Cluster Generator
          options:
            - dev
            - qa
            - prod
          defaultValue: dev
          section: Deployment Environment
      version: 1.0.0
    - template:
        metadata: {}
        instanceTemplate:
          metadata: {}
        pro:
          enabled: true
        helmRelease:
          chart:
            version: 0.20.1
          values: |-
            sync:
              toHost:
                ingresses:
                  enabled: true
            # Checkout https://vcluster.com/pro/docs/ for more config options
        accessPoint:
          ingress: {}
        spaceTemplate:
          metadata: {}
      version: 0.0.0
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
status: {}
---
kind: VirtualClusterTemplate
apiVersion: management.loft.sh/v1
metadata:
  name: preview-template
spec:
  displayName: vCluster Preview Template
  template:
    metadata:
      labels:
        loft.sh/import-argocd: 'true'
      annotations:
        sleepmode.loft.sh/delete-after: '72000'
        loft.sh/require-ingress-authentication: 'true'
        sleepmode.loft.sh/sleep-after: '600'
        sleepmode.loft.sh/ignore-user-agents: 'argo*'
    objects: |
      apiVersion: v1
      kind: Namespace
      metadata:
        name: preview-hello-world-app
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-login-secret
        namespace: preview-hello-world-app
        labels:
          loft.sh/project-secret-name: ghcr-login-secret
      data:
        .dockerconfigjson: e30K
      type: kubernetes.io/dockerconfigjson
    access:
      rules:
        - teams:
            - loft-admins
          clusterRole: cluster-admin
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.22.4
      values: |-
        external:
          platform:
            autoSleep:
              afterInactivity: 10800
              autoWakeup:
                schedule: 11 8-16 * * 1-5
            autoDelete:
              afterInactivity: 120000
        sync:
          toHost:
            ingresses:
              enabled: true
            secrets:
              all: true

        controlPlane:
          # Use an embedded managed etcd server instead of using the k3s default SQLite backend
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
        policies:
          limitRange:
            enabled: true
          podSecurityStandard: baseline
          resourceQuota:
            enabled: true
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  access:
    - verbs:
        - '*'
      subresources:
        - '*'
      users:
        - admin
---
apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: sleepy-vcluster-template
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  displayName: Sleepy vCluster Template
  description: This template deploys a sleepy virtual cluster
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        name: vcluster
        repo: https://loft-demos.github.io/vcluster-charts
        version: 0.22.4
      values: |
        sync:
          toHost:
            ingresses:
              enabled: true

        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          coredns:
            embedded: true
          statefulSet:
            image:
              repository: "loft-demos/vcluster-pro"
              tag: "0.22.4-k8s.{{ .Values.k8sVersion }}"
        
        external:
          platform:
            autoSleep:
              afterInactivity: 60
            autoDelete:
              afterInactivity: 120
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  parameters:
    - variable: sleepAfter
      label: Sleep After Inactivity (minutes)
      type: number
      defaultValue: '2'
    - variable: k8sVersion
      label: k8sVersion
      description: Please select Kubernetes version
      options:
        - v1.32.2
        - v1.31.6
        - v1.30.10
        - v1.29.14
      defaultValue: v1.31.6
  access:
    - verbs:
        - get
      users:
        - '*'
